### ISSUE TITLE
Can support env configuration for Yaml?

### ISSUE THREAD

**Issue by snice** [fastify/fastify-cli#81]
**.env.yml**
```yml

FASTIFY_PORT : 3000
FASTIFY_LOG_LEVEL : info
MONGODB_URL : mongodb://127.0.0.1:32768/dragapp
DEV_WORKSPACE_PATH : ~/Downloads/drag_dev/
HTTP_PROXY:
      upstream : http://127.0.0.1
      prefix : /dev_preview/:uId

```

https://github.com/jrwells/env-yaml
